name: pytorch
channels:
 - conda-forge
 - pytorch
dependencies:
  - python=3.6
  - ipython
  - six
  - tqdm
  - pyyaml
  - pyzmq
  - numpy
  - matplotlib
  - h5py
  - scipy
  - torchvision
  - pytorch
